include ../build_config.mk

SOURCES= \
	db_factory_kreonR.cc	\
#	db_factory_eutropiadb.cc \
#	db_factory_rocksdb.cc

OBJECTS=$(SOURCES:.cc=.o)

all: $(SOURCES) $(OBJECTS)


db_factory_kreonR.o: db_factory_kreonR.cc
	$(CC) $(CFLAGS) $(TUCDB_LIBS_)-I $(TUCDB_FLAGS) -I. -I.. -I$(TUCDB_INC)  -I$(EDB_INC) -c db_factory_kreonR.cc

#db_factory_tucanaclientdb.o: db_factory_tucanaclientdb.cc
#	$(CC) $(CFLAGS) $(TUCDB_LIBS) $(TUCDB_FLAGS) -I. -I.. -I$(TUCDB_INC) -I$(EDB_INC) -c db_factory_tucanaclientdb.cc

#db_factory_berkeleydb.o: db_factory_berkeleydb.cc 
#	$(CC) $(CFLAGS) -I. -I.. -I$(BDB_INC) -c db_factory_berkeleydb.cc

db_factory_eutropiadb.o: db_factory_eutropiadb.cc
	$(CC) $(CFLAGS) -I. -I.. -I$(EDB_INC) -c db_factory_eutropiadb.cc

#db_factory_kyotodb.o: db_factory_kyotodb.cc
#	$(CC) $(CFLAGS) -I. -I.. -I$(KDB_INC) -c db_factory_kyotodb.cc

#db_factory_leveldb.o: db_factory_leveldb.cc
#	$(CC) $(CFLAGS) -I. -I.. -I$(LDB_INC) -c db_factory_leveldb.cc

#db_factory_perconaft.o: db_factory_perconaft.cc 
#	$(CC) $(CFLAGS) -I. -I.. -I$(PFT_INC) -c db_factory_perconaft.cc

#db_factory_rocksdb.o: db_factory_rocksdb.cc
#	$(CC) $(CFLAGS) -I. -I.. -I$(RDB_INC) -c db_factory_rocksdb.cc

db_factory_nulldb.o: db_factory_nulldb.cc
	$(CC) $(CFLAGS) -I. -I.. -c db_factory_nulldb.cc

clean:
	$(RM) *.o

