image: carvicsforth/arch_carv:latest

stages:
  - build
  - deploy

build_gcc:
  stage: build
  script:
    - mkdir -p build;cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - make mkfs.kreon;make kreon;make kreon-shared
    - make ycsb-edb;make test_scans;make test_spills;make test_spillscans;make test_deletes;

build_clang:
  stage: build
  script:
    - mkdir -p build;cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
    - make mkfs.kreon;make kreon;make kreon-shared
    - make ycsb-edb;make test_scans;make test_spills;make test_spillscans;make test_deletes;

build_rdma_gcc:
  image: carvicsforth/ubuntu_carv:latest
  stage: build
  script:
    - mkdir -p build;cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10
    - make all

build_rdma_clang:
  image: carvicsforth/ubuntu_carv:latest
  stage: build
  script:
    - mkdir -p build;cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang-10 -DCMAKE_CXX_COMPILER=clang++-10
    - make all

build_clang-tidy:
  stage: build
  script:
    - mkdir -p build;cd build
    - cmake .. "-DCMAKE_C_CLANG_TIDY=/bin/clang-tidy;-checks=*"
    - make mkfs.kreon;make kreon;make kreon-shared
    - make ycsb-edb;make test_scans;make test_spills;make test_spillscans;make test_deletes;

install_kreon:
  image: carvicsforth/ubuntu_carv:latest
  stage: deploy
  variables:
    KREON_INSTALL_PATH : "installtest"
  script:
    - mkdir -p build;cd build
    - cmake .. -DKREON_BUILD_CPACK=True -DCMAKE_BUILD_TYPE=Debug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10
    - make install DESTDIR=$KREON_INSTALL_PATH;mv $KREON_INSTALL_PATH ../scripts/;cd ../scripts
    - ./verify-installed-files.py $KREON_INSTALL_PATH

pre-commit:
  stage: build
  script:
    - ./scripts/pre-commit-CI.sh

pre-merge:
  stage: build
  script:
    - ./scripts/pre-merge-CI.sh
  only:
    - merge_requests
