---
image: carvicsforth/arch_carv:latest
variables:
    FF_GITLAB_REGISTRY_HELPER_IMAGE: 1
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
    CTEST_OUTPUT_ON_FAILURE: 1
    NVME0: /nvme0

include: scripts/CI/yml/*.yml
stages:
    - debug_build
    - lint
    - release_build
    - debug_test
    - release_test
    - install
    - deploy
