# File: Makefile
# Author: Michalis Vardoualkis <mvard@ics.forth.gr>

CC=gcc -std=gnu99
CFLAGS=-Wall -g
LFLAGS=-lrdmacm -libverbs -lpthread -D_GNU_SOURCE

.PHONY: all clean

all: libturdma.a tu_rdma.o 

memory_regions.o: memory_regions.c memory_regions.h klist.h
	$(CC) $(CFLAGS) -c $<

tu_rdma.o: tu_rdma.c tu_rdma.h memory_regions.o
	$(CC) $(CFLAGS) -c $<

test_rdma: test_rdma.c memory_regions.o tu_rdma.o
	$(CC)  -o $@ $^ $(CFLAGS) $(LFLAGS)

libturdma.a: memory_regions.o tu_rdma.o
	ar rcs $@ $^

clean:
	@rm -f *.o test_rdma libturdma.a
