all:
  vars:
    username: 'mvard'
    repo_path: '~/HEutropia'
    results_folder: '~/RESULTS'
    exe_path: '~/HEutropia/build'
    LD_LIBRARY_PATH: '/home1/public/mvard/zookeeper_c/libs'

kreon:
  vars:
    dmap: false
  hosts:
    sith4_0:
      ansible_ssh_host: sith4
      listen_port: 5050
      device: '/nvme/disk0.dat'
      device_size: 50
      taskset: '0-7,16-23'
    sith4_1:
      ansible_ssh_host: sith4
      listen_port: 5051
      device: '/nvme/disk1.dat'
      device_size: 50
      taskset: '8-15,24-31'

ycsb:
  vars:
    db_num: '1'
    threads: '16'
  hosts:
    jedi4:
      listen_port: '0000'
