# file: tucana.yml
# author: Michalis Vardoulakis <mvard@ics.forth.gr>

# TODO Automate regions creation and add it to ansible script
- hosts: kreon
  remote_user: '{{ username }}'
  gather_facts: False
  tasks:
    - name: 'Cleanup failed experiments'
      command: "pkill --signal SIGKILL tucanaserver"
      ignore_errors: True
      failed_when: False

    - name: 'Load dmap'
      when: dmap
      command: "sudo ./00_load-it-dev.sh {{ device }}"
      args:
        chdir: '/usr/local/dmap'

    - name: 'Format device'
      # In the command below the number arguments need to be 1 0 for real
      # devices and 1 1 for files
      command: "sudo ./mkfs.eutropia.single.sh {{ device }} 1 1"
      args:
        chdir: '{{ repo_path }}/YCSB-CXX/'

    - name: 'Change device owner'
      when: not dmap
      command: "sudo chown {{ username }} {{ device }}"

    - name: 'Change dmap device owner'
      when: dmap
      command: "sudo chown {{ username }} /dev/dmap/dmap1"

    - name: 'Start a tucanaserver (with dmap)'
      when: dmap
      shell: "taskset -c {{ taskset }} {{ repo_path }}/build/TucanaServer/tucanaserver
                  {{ listen_port }} /dev/dmap/dmap1 {{ device_size }}"
      environment:
        LD_LIBRARY_PATH: "{{ LD_LIBRARY_PATH }}"

    - name: 'Start a tucanaserver (without dmap)'
      when: not dmap
      shell: "taskset -c {{ taskset }} {{ repo_path }}/build/TucanaServer/tucanaserver
                  {{ listen_port }} {{ device }} {{ device_size }}"
      environment:
        LD_LIBRARY_PATH: "{{ LD_LIBRARY_PATH }}"

    - name: 'Unload dmap'
      when: dmap
      command: "sudo ./00_remove-it.sh"
      args:
        chdir: '/usr/local/dmap'

    - name: 'Revert device ownership change'
      when: not dmap
      command: "sudo chown root {{ device }}"
