- hosts: kreon ycsb
  remote_user: "{{ username }}"
  gather_facts: False
  tasks:
    - name: 'Cleanup failed tasks'
      command: 'pkill --signal SIGKILL iostat && pkill --signal SIGKILL mpstat'
      failed_when: False
      ignore_errors: True

- hosts: ycsb
  remote_user: "{{ username }}"
  gather_facts: False
  tasks:
    - name: 'Cleanup previous results'
      command: 'rm -rf {{ results_folder }}'
      ignore_errors: True

- hosts: kreon ycsb
  remote_user: "{{ username }}"
  gather_facts: False
  tasks:
    - name: 'Create experiment results folder'
      file:
        path: '{{ results_folder }}/{{ item }}/{{ ansible_ssh_host }}-{{ listen_port }}'
        state: directory
      with_items:
        - "load_a"
        - "run_a"
        - "run_b"
        - "run_c"
        - "run_f"
        - "run_d"

- hosts: localhost
  gather_facts: False
  tasks:
    - name: 'Upload ycsb_execution_plans folder'
      command: "rsync -r ycsb_execution_plans {{ username }}@shark:{{ exe_path }}"

# LOAD A
- hosts: kreon ycsb
  remote_user: "{{ username }}"
  gather_facts: False
  tasks:
    - name: 'Start monitoring tools'
      async: 10000
      poll: 0
      command: "./start_statistics.sh {{results_folder }}/load_a/{{ ansible_ssh_host }}-{{ listen_port }}"
      args:
        chdir: '{{ repo_path }}/YCSB-CXX'

- hosts: ycsb
  remote_user: "{{ username }}"
  gather_facts: False
  tasks:
    - name: 'YCSB Load A'
      shell: "YCSB-CXX/ycsb-kreon -dbnum {{ db_num }}
                  -threads {{ threads }}
                  -e ycsb_execution_plans/execution_plan_la.txt
                  -o {{ results_folder }}"
      environment:
        LD_LIBRARY_PATH: "{{ LD_LIBRARY_PATH }}"
      ignore_errors: True
      args:
        chdir: '{{ exe_path }}'


- hosts: kreon ycsb
  gather_facts: False
  tasks:
    - name: 'Stop monitoring tools'
      command: "./stop_statistics.sh {{results_folder }}/load_a/{{ ansible_ssh_host }}-{{ listen_port }}"
      args:
        chdir: '{{ repo_path }}/YCSB-CXX'

# RUN A
- hosts: kreon ycsb
  remote_user: "{{ username }}"
  gather_facts: False
  tasks:
    - name: 'Start monitoring tools'
      async: 10000
      poll: 0
      command: "./start_statistics.sh {{results_folder }}/run_a/{{ ansible_ssh_host }}-{{ listen_port }}"
      args:
        chdir: '{{ repo_path }}/YCSB-CXX'

- hosts: ycsb
  remote_user: "{{ username }}"
  gather_facts: False
  tasks:
    - name: 'YCSB Run A'
      shell: "YCSB-CXX/ycsb-kreon -dbnum {{ db_num }}
                  -threads {{ threads }}
                  -e ycsb_execution_plans/execution_plan_ra.txt
                  -o {{ results_folder }}"
      environment:
        LD_LIBRARY_PATH: "{{ LD_LIBRARY_PATH }}"
      ignore_errors: True
      args:
        chdir: '{{ exe_path }}'

- hosts: kreon ycsb
  gather_facts: False
  tasks:
    - name: 'Stop monitoring tools'
      command: "./stop_statistics.sh {{results_folder }}/run_a/{{ ansible_ssh_host }}-{{ listen_port }}"
      args:
        chdir: '{{ repo_path }}/YCSB-CXX'

# RUN B
- hosts: kreon ycsb
  remote_user: "{{ username }}"
  gather_facts: False
  tasks:
    - name: 'Start monitoring tools'
      async: 10000
      poll: 0
      command: "./start_statistics.sh {{results_folder }}/run_b/{{ ansible_ssh_host }}-{{ listen_port }}"
      args:
        chdir: '{{ repo_path }}/YCSB-CXX'

- hosts: ycsb
  remote_user: "{{ username }}"
  gather_facts: False
  tasks:
    - name: 'YCSB Run B'
      shell: "YCSB-CXX/ycsb-kreon -dbnum {{ db_num }}
                  -threads {{ threads }}
                  -e ycsb_execution_plans/execution_plan_rb.txt
                  -o {{ results_folder }}"
      environment:
        LD_LIBRARY_PATH: "{{ LD_LIBRARY_PATH }}"
      ignore_errors: True
      args:
        chdir: '{{ exe_path }}'

- hosts: kreon ycsb
  gather_facts: False
  tasks:
    - name: 'Stop monitoring tools'
      command: "./stop_statistics.sh {{results_folder }}/run_b/{{ ansible_ssh_host }}-{{ listen_port }}"
      args:
        chdir: '{{ repo_path }}/YCSB-CXX'

# RUN C
- hosts: kreon ycsb
  remote_user: "{{ username }}"
  gather_facts: False
  tasks:
    - name: 'Start monitoring tools'
      async: 10000
      poll: 0
      command: "./start_statistics.sh {{results_folder }}/run_c/{{ ansible_ssh_host }}-{{ listen_port }}"
      args:
        chdir: '{{ repo_path }}/YCSB-CXX'

- hosts: ycsb
  remote_user: "{{ username }}"
  gather_facts: False
  tasks:
    - name: 'YCSB Run C'
      shell: "YCSB-CXX/ycsb-kreon -dbnum {{ db_num }}
                  -threads {{ threads }}
                  -e ycsb_execution_plans/execution_plan_rc.txt
                  -o {{ results_folder }}"
      environment:
        LD_LIBRARY_PATH: "{{ LD_LIBRARY_PATH }}"
      ignore_errors: True
      args:
        chdir: '{{ exe_path }}'

- hosts: kreon ycsb
  gather_facts: False
  tasks:
    - name: 'Stop monitoring tools'
      command: "./stop_statistics.sh {{results_folder }}/run_c/{{ ansible_ssh_host }}-{{ listen_port }}"
      args:
        chdir: '{{ repo_path }}/YCSB-CXX'

# RUN F
- hosts: kreon ycsb
  remote_user: "{{ username }}"
  gather_facts: False
  tasks:
    - name: 'Start monitoring tools'
      async: 10000
      poll: 0
      command: "./start_statistics.sh {{results_folder }}/run_f/{{ ansible_ssh_host }}-{{ listen_port }}"
      args:
        chdir: '{{ repo_path }}/YCSB-CXX'

- hosts: ycsb
  remote_user: "{{ username }}"
  gather_facts: False
  tasks:
    - name: 'YCSB Run F'
      shell: "YCSB-CXX/ycsb-kreon -dbnum {{ db_num }}
                  -threads {{ threads }}
                  -e ycsb_execution_plans/execution_plan_rf.txt
                  -o {{ results_folder }}"
      environment:
        LD_LIBRARY_PATH: "{{ LD_LIBRARY_PATH }}"
      ignore_errors: True
      args:
        chdir: '{{ exe_path }}'

- hosts: kreon ycsb
  gather_facts: False
  tasks:
    - name: 'Stop monitoring tools'
      command: "./stop_statistics.sh {{results_folder }}/run_f/{{ ansible_ssh_host }}-{{ listen_port }}"
      args:
        chdir: '{{ repo_path }}/YCSB-CXX'

# RUN D
- hosts: kreon ycsb
  remote_user: "{{ username }}"
  gather_facts: False
  tasks:
    - name: 'Start monitoring tools'
      async: 10000
      poll: 0
      command: "./start_statistics.sh {{results_folder }}/run_d/{{ ansible_ssh_host }}-{{ listen_port }}"
      args:
        chdir: '{{ repo_path }}/YCSB-CXX'

- hosts: ycsb
  remote_user: "{{ username }}"
  gather_facts: False
  tasks:
    - name: 'YCSB Run D'
      shell: "YCSB-CXX/ycsb-kreon -dbnum {{ db_num }}
                  -threads {{ threads }}
                  -e ycsb_execution_plans/execution_plan_rd.txt
                  -o {{ results_folder }}"
      environment:
        LD_LIBRARY_PATH: "{{ LD_LIBRARY_PATH }}"
      ignore_errors: True
      args:
        chdir: '{{ exe_path }}'

- hosts: kreon ycsb
  gather_facts: False
  tasks:
    - name: 'Stop monitoring tools'
      command: "./stop_statistics.sh {{results_folder }}/run_d/{{ ansible_ssh_host }}-{{ listen_port }}"
      args:
        chdir: '{{ repo_path }}/YCSB-CXX'

- hosts: kreon
  gather_facts: False
  tasks:
    - name: 'Stop servers'
      command: "pkill --signal SIGINT tucanaserver"
